# Generated by Django 5.2.7 on 2026-01-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_friend_friend1_alter_friend_friend2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
