# Generated by Django 5.2.7 on 2026-01-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pp/default.jpg', null=True, upload_to='pp'),
        ),
    ]
