# Generated by Django 5.2.7 on 2026-01-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_counter', to='base.room'),
        ),
    ]
