# Generated by Django 5.2.7 on 2026-01-18 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_counter_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_counter', to='base.room'),
        ),
    ]
