# Generated by Django 5.2.7 on 2026-01-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_counter_user_counter_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
