# Generated by Django 5.2.7 on 2026-01-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_room_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['created', 'updated']},
        ),
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
