# Generated by Django 5.2.7 on 2026-01-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_room_created_alter_room_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
