# Generated by Django 6.0.2 on 2026-02-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_genre_room_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_room', to='base.genre'),
        ),
    ]
