# Generated by Django 6.0.2 on 2026-02-26 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_room_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='joined_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
